name: ci-cd-pipeline

on:
  push:
  schedule:
    - cron: "0 1 * * 4"
jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Python 3.8
        run: task wheel PYTHON_VERSION=3.8.13
      - name: Python 3.9
        run: task wheel PYTHON_VERSION=3.9.13
      - name: Python 3.10
        run: task wheel PYTHON_VERSION=3.10.4
      - name: Archive wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: dist/*
      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true
      - name: Publish to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
