name: ci-cd-pipeline

# TODO: Once this works, run automatically every night to check compatibility with most recent toolchain

on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker-compose build
      - name: Test
        run: docker-compose run test
