name: ci-cd-pipeline

on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    container: python:3.9.12-slim-bullseye
    steps:
      - uses: actions/checkout@v2
      - name: apt setup
        run: |
          apt update
          apt-get install -y build-essential tar curl zip unzip git pkg-config
      - name: vcpkg setup
        run: |
          cd /tmp
          git clone https://github.com/microsoft/vcpkg
          ./vcpkg/bootstrap-vcpkg.sh
          export CXXFLAGS="$CXXFLAGS -fPIC"
          ./vcpkg/vcpkg install seal[no-throw-tran] kuku log4cplus cppzmq flatbuffers jsoncpp apsi
      - name: Python setup
        run: |
          pip install poetry
          poetry install
          poetry run pip install --verbose .
        env:
          VCPKG_INSTALLED_DIR: /tmp/vcpkg/installed
      - name: Formatting
        if: always()
        run: |
          poetry run black --check *.py
      - name: Sorted Imports
        if: always()
        run: |
          poetry run isort --check-only --profile black --line-length 88 *.py
